### ISSUE TITLE
One node can be allocated to only one user

### ISSUE THREAD

**Issue by Shimmer93** [turingaicloud/quickstart#1]
Issue: 
Even when a user has only requested 1 cpu or 1 gpu and more resources are available, other users won’t be able to apply to the same node. 

Reproduce:
In tuxiv.conf:
```
job:
    name: test
    general:
      - nodes=1
      - ntasks=1
      - cpus-per-task=1
      - gres=gpu:1
```

Expect behavior:
Node 1 has 39 CPUs and 7 GPUs available,  and other users can use the rest of resources
